// Single import surface for the lucide icons used as UI chrome (buttons,
// status indicators, controls). Content-flavor emoji (content-type icons,
// storyboard shot emoji, the one-off celebration moment) are intentionally
// NOT here — those are user-facing personality, not interface chrome.
export {
  PenLine,
  Palette,
  Clapperboard,
  Pause,
  Play,
  Maximize,
  Check,
  X,
  CheckCircle2,
  AlertTriangle,
  Megaphone,
  Lock,
  Zap,
  Share2,
  Trash2,
  Download,
  ExternalLink,
  Copy,
  ChevronUp,
  ChevronDown,
  Sparkles,
  PartyPopper,
  Camera,
} from 'lucide-react'
